
# ...existing code...
from flask import current_app

def some_interface_function():
    # ...existing code...
    Calibration_transformation = current_app.config.get('Calibration_transformation', None)
    if Calibration_transformation is None:
        logger.error("Calibration transformation not available.")
        return
    # Use Calibration_transformation in the interface logic
    # ...existing code...
# ...existing code...