configurations_info = {
    'Current Acquisition Time (µs)': {
        'get_command': 'GetAcquisitionTime',
        'set_command': 'SetAcquisitionTime',
        'description': 'Determines the interval of acquiring point cloud or 2D camera images.',
        'min_command': 'GetAcquisitionTimeMin',
        'max_command': 'GetAcquisitionTimeMax',
        'default_command': 'GetAcquisitionTimeDefault',
        'type': 'int',
    },
    'Current Exposure Time Limit (µs)': {
        'get_command': 'GetExposureTimeLimit',
        'set_command': 'SetExposureTimeLimit',
        'description': 'Sets the exposure time limit. The LED projector frequency will be adjusted accordingly.',
        'min_command': 'GetExposureTimeLimitMin',
        'max_command': 'GetExposureTimeLimitMax',
        'default_command': 'GetExposureTimeLimitDefault',
        'type': 'int',
    },
    'Current Exposure Time (µs)': {
        'get_command': 'GetExposureTime',
        'set_command': 'SetExposureTime',
        'description': 'Sets the exposure time of the built-in camera chip.',
        'min_command': 'GetExposureTimeMin',
        'max_command': 'GetExposureTimeMax',
        'default_command': 'GetExposureTimeDefault',
        'type': 'int',
    },
    'Z Start (mm)': {
        'get_command': 'GetZmin',
        'set_command': 'SetZmin',
        'description': 'Sets the minimum measuring range in Z.',
        'type': 'float',
    },
    'Z End (mm)': {
        'get_command': 'GetZmax',
        'set_command': 'SetZmax',
        'description': 'Sets the maximum measuring range in Z.',
        'type': 'float',
    },
    'Contrast Comparison Filter': {
        'get_command': 'GetContrastComparisonFilterMinPhase',
        'set_command': 'SetContrastComparisonFilterMinPhase',
        'description': 'Sets the filter threshold of the contrast comparison filter where 1 is the highest possible contrast and 0 is no contrast at all.',
        'min_command': 'GetContrastComparisonFilterMinPhaseMin',
        'max_command': 'GetContrastComparisonFilterMinPhaseMax',
        'default_command': 'GetContrastComparisonFilterMinPhaseDefault',
        'type': 'float',
    },
    'SDK Queue Size': {
        'get_command': 'GetSDKQueueSize',
        'set_command': 'SetSDKQueueSize',
        'description': 'Sets the maximum number of point clouds buffered in SDK.',
        'default_command': 'GetSDKQueueSizeDefault',
        'type': 'int',
    },
    'Trigger Source': {
        'get_command': 'GetTriggerSource',
        'set_command': 'SetTriggerSource',
        'description': 'Sets the trigger source of the 3D sensor.',
        'options': {
            '0': 'Internal trigger',
            '1': 'Software trigger',
            '2': 'Hardware trigger (I/O1)',
            '3': 'Hardware trigger (I/O2)',
            '4': 'Hardware trigger (I/O3)',
            '5': 'Hardware trigger (I/O4)',
        },
        'default_command': 'GetTriggerSourceDefault',
        'type': 'enum',
    },
    'Sensor Enable': {
        'get_command': 'GetSensorEnable',
        'set_command': 'SetSensorEnable',
        'description': 'Activates the I/O data acquisition of the 3D sensor.',
        'options': {
            '0': 'Off',
            '1': 'I/O Line 1',
            '2': 'I/O Line 2',
            '3': 'I/O Line 3',
            '4': 'I/O Line 4',
        },
        'default_command': 'GetSensorEnableDefault',
        'type': 'enum',
    },
    'Sensor Mode': {
        'get_command': 'GetSensorMode',
        'set_command': 'SetSensorMode',
        'description': 'Configures the 3D sensor to generate point cloud or 2D images.',
        'options': {
            '4': '3D Point Cloud',
            '5': '2D Camera Images',
        },
        'default_command': 'GetSensorModeDefault',
        'type': 'enum',
    },
    'Gain': {
        'get_command': 'GetGain',
        'set_command': 'SetGain',
        'description': 'Sets the gain of the built-in camera chip.',
        'min_command': 'GetGainMin',
        'max_command': 'GetGainMax',
        'default_command': 'GetGainDefault',
        'type': 'int',
    },
    'Subsampling': {
        'get_command': 'GetSubSampling',
        'set_command': 'SetSubSampling',
        'description': 'Activates the subsampling in the built-in camera chip.',
        'options': {
            '0': 'Disabled',
            '1': 'Enabled',
        },
        'default_command': 'GetSubSamplingDefault',
        'type': 'enum',
    },
    'LED Power (%)': {
        'get_command': 'GetLEDPower',
        'set_command': 'SetLEDPower',
        'description': 'Sets the brightness of the sensor’s LED projector.',
        'min_command': 'GetLEDPowerMin',
        'max_command': 'GetLEDPowerMax',
        'default_command': 'GetLEDPowerDefault',
        'type': 'int',
    },
    'User LED': {
        'get_command': 'GetUserLED',
        'set_command': 'SetUserLED',
        'description': 'Sets User LED color.',
        'options': {
            '0': 'Off',
            '1': 'Green',
            '2': 'Red',
            '3': 'Orange',
        },
        'default_command': 'GetUserLEDDefault',
        'type': 'enum',
    },
    'LED Activate': {
        'get_command': 'GetLEDActivate',
        'set_command': 'SetLEDActivate',
        'description': 'Activates/deactivates the built-in LED projector.',
        'options': {
            '0': 'Deactivate',
            '1': 'Activate',
        },
        'default_command': 'GetLEDActivateDefault',
        'type': 'enum',
    },
    'Extended Measuring Range': {
        'get_command': 'GetEnableExtendedMeasuringRange',
        'set_command': 'SetEnableExtendedMeasuringRange',
        'description': 'Activates/deactivates the extended working area.',
        'options': {
            '0': 'Deactivate',
            '1': 'Activate',
        },
        'default': '0',  # Specify default value directly if no command to get it
        'type': 'enum',
    },
}
